import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { DashboardLayout } from "@/components/layout/Dashboard-Layout";

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Wingman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} font-sans antialiased text-black`}
        suppressHydrationWarning={true}
      >
        <DashboardLayout>{children}</DashboardLayout>
      </body>
    </html>
  );
}
